force-app/main/default/objects/Tag_Anything__c/Tag_Anything__c.object-meta.xml
<CustomObject>
    <label>Tag</label>
    <nameField>
        <label>Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tag_Anything__c/fields/Icon__c.field-meta.xml
<CustomField>
    <fullName>Icon__c</fullName>
    <label>Icon</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tag_Anything__c/fields/Internal_Value__c.field-meta.xml
<CustomField>
    <fullName>Internal_Value__c</fullName>
    <label>Internal Value</label>
    <length>6</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Tag_Anything__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tag_Anything__c/fields/Label_Color__c.field-meta.xml
<CustomField>
    <fullName>Label_Color__c</fullName>
    <defaultValue>&#39;#000000&#39;</defaultValue>
    <label>Label Color</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tag_Anything__c/fields/Tag_Color__c.field-meta.xml
<CustomField>
    <fullName>Tag_Color__c</fullName>
    <defaultValue>&#39;#EAEAEA&#39;</defaultValue>
    <label>Tag Color</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TagAnythingBrowserController.cls
public with sharing class TagAnythingBrowserController {

    @AuraEnabled(Cacheable=true)
    public static List<Tag_Anything__c> requireTags(String search_key){
        List<list<SObject>> search_tags = new List<list<SObject>>();
        search_tags = [FIND :search_key IN ALL FIELDS 
                       RETURNING Tag_Anything__c(Name, Icon__c, Internal_Value__c, Label_Color__c, Tag_Color__c WHERE Is_Active__c = true ORDER BY Name DESC) 
                       LIMIT 20];
        return new List<Tag_Anything__c>((List<Tag_Anything__c>)search_tags[0]); 
    }
}