force-app/main/default/objects/Tag_Anything__c/Tag_Anything__c.object-meta.xml
<CustomObject>
    <label>Tag</label>
    <nameField>
        <label>Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tag_Anything__c/fields/Internal_Value__c.field-meta.xml
<CustomField>
    <fullName>Internal_Value__c</fullName>
    <label>Internal Value</label>
    <length>6</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Tag_Anything__c/fields/Tag_Color__c.field-meta.xml
<CustomField>
    <fullName>Tag_Color__c</fullName>
    <defaultValue>&#39;#EAEAEA&#39;</defaultValue>
    <label>Tag Color</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TagAnythingBrowserControllerTest.cls
@isTest
public with sharing class TagAnythingBrowserControllerTest {

    @isTest
    public static void requireNewTag() {
        Tag_Anything__c new_tag = new Tag_Anything__c(
            Name = 'New',
            Internal_Value__c = 'New'
        );
        insert new_tag;
        Id [] fixed_search_results = new Id[]{new_tag.Id};
        Test.setFixedSearchResults(fixed_search_results);
        Test.startTest();
        List<Tag_Anything__c> new_test = TagAnythingBrowserController.requireTags('test');
        Test.stopTest();
        System.assertEquals('New', new_test[0].Internal_Value__c);
    }

    @isTest
    public static void requireBugTag(){
        Tag_Anything__c bug_tag = new Tag_Anything__c(
            Name = 'Bug',
            Internal_Value__c = 'Bug',
            Tag_Color__c = '#FF0000'
        );
        insert bug_tag;
        Id [] fixed_search_results = new Id[]{bug_tag.Id};
        Test.setFixedSearchResults(fixed_search_results);
        Test.startTest();
        List<Tag_Anything__c> bug_test = TagAnythingBrowserController.requireTags('Bug');
        Test.stopTest();
        System.assertEquals('#FF0000', bug_test[0].Tag_Color__c);
    }
    
}