force-app/main/default/objects/Tag_Anything__c/Tag_Anything__c.object-meta.xml
<CustomObject>
    <label>Tag</label>
    <nameField>
        <label>Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tag_Anything__c/fields/Internal_Value__c.field-meta.xml
<CustomField>
    <fullName>Internal_Value__c</fullName>
    <label>Internal Value</label>
    <length>6</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/TagAnythingDisplayerControllerTest.cls
@isTest
private with sharing class TagAnythingDisplayerControllerTest {

    @TestSetup
    static void makeData() {
        List<Tag_Anything__c> tags = new List<Tag_Anything__c>();
        tags.add(new Tag_Anything__c(
            Name = 'Tag 1',
            Internal_Value__c = 'Tag1'
        ));
        tags.add(new Tag_Anything__c(
            Name = 'Tag 2',
            Internal_Value__c = 'Tag2'
        ));

        insert tags;
    }

    @isTest
    static void testRequireCurrentTagsReturningOneTag() {
        List<Tag_Anything__c> tags = TagAnythingDisplayerController.requireCurrentTags('Tag1');
        System.assertEquals(1, tags.size(), 'Should return only 1 tag');
        System.assertEquals('Tag 1', tags.get(0).Name, 'Should return Tag 1');
    }

    @isTest
    static void testRequireCurrentTagsReturningTwoTags() {
        List<Tag_Anything__c> tags = TagAnythingDisplayerController.requireCurrentTags('Tag1,Tag2');
        System.assertEquals(2, tags.size(), 'Should return 2 tags');
        System.assertEquals('Tag 2', tags.get(0).Name, 'Should return Tag 2');
        System.assertEquals('Tag 1', tags.get(1).Name, 'Should return Tag 1');
    }

    @isTest
    static void testRequireCurrentTagsReturningNoMatchValues() {
        List<Tag_Anything__c> tags = TagAnythingDisplayerController.requireCurrentTags('Tag');
        System.assertEquals(0, tags.size(), 'Should return 0 tags');
    }

    @isTest
    static void testRequireCurrentTagsWithNullParam() {
        List<Tag_Anything__c> tags = TagAnythingDisplayerController.requireCurrentTags(null);
        System.assertEquals(0, tags.size(), 'Should return 0 tags');
    }

    @isTest
    static void testRequireCurrentTagsWithEmptyParam() {
        List<Tag_Anything__c> tags = TagAnythingDisplayerController.requireCurrentTags(' ');
        System.assertEquals(0, tags.size(), 'Should return 0 tags');
    }
}