force-app/main/default/objects/Tag_Anything__c/Tag_Anything__c.object-meta.xml
<CustomObject>
    <label>Tag</label>
    <nameField>
        <label>Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tag_Anything__c/fields/Icon__c.field-meta.xml
<CustomField>
    <fullName>Icon__c</fullName>
    <label>Icon</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tag_Anything__c/fields/Internal_Value__c.field-meta.xml
<CustomField>
    <fullName>Internal_Value__c</fullName>
    <label>Internal Value</label>
    <length>6</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Tag_Anything__c/fields/Label_Color__c.field-meta.xml
<CustomField>
    <fullName>Label_Color__c</fullName>
    <defaultValue>&#39;#000000&#39;</defaultValue>
    <label>Label Color</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tag_Anything__c/fields/Tag_Color__c.field-meta.xml
<CustomField>
    <fullName>Tag_Color__c</fullName>
    <defaultValue>&#39;#EAEAEA&#39;</defaultValue>
    <label>Tag Color</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TagAnythingDisplayerController.cls
public without sharing class TagAnythingDisplayerController {

    @AuraEnabled(cacheable=true)
    public static List<Tag_Anything__c> requireCurrentTags(String current_tags) {
        List<Tag_Anything__c> tags_to_return = new List<Tag_Anything__c>();
        if (String.isNotBlank(current_tags)) {
            current_tags = current_tags.deleteWhitespace();
            List<String> current_tags_to_check = current_tags.split(',');
            tags_to_return = [SELECT Id, Name, Icon__c, Internal_Value__c, Label_Color__c, Tag_Color__c
                                FROM Tag_Anything__c
                                WHERE Internal_Value__c IN :current_tags_to_check
                                ORDER BY Name DESC];
        }
        return tags_to_return;
    }
}